// Self-test for generate-agents.mjs (FRW-BL-037).
// Run: node framework/agents/generate-agents.test.mjs
import { buildAll, renderAgent, resolveTools, resolveDisallowedTools, shortModel, NATIVE_AGENTS } from './generate-agents.mjs';
import { AGENT_REGISTRY_DATA } from './registry.data.mjs';
import { readFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, resolve } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, '..', '..');
const AGENTS_DIR = join(REPO_ROOT, '.claude', 'agents');

let pass = 0, fail = 0;
function ok(label, cond) { if (cond) { pass++; console.log(`  ✓ ${label}`); } else { fail++; console.log(`  ✗ ${label}`); } }

console.log('generate-agents self-test\n');

// --- parse the frontmatter of a generated def --------------------------------
/** Minimal frontmatter parser: returns { fm: rawString, body, hasFences }. */
function splitDef(content) {
  const m = /^---\n([\s\S]*?)\n---\n([\s\S]*)$/.exec(content);
  return m ? { fm: m[1], body: m[2], ok: true } : { fm: '', body: '', ok: false };
}
/** Read a top-level scalar value from the frontmatter (string after `key: `). */
function fmScalar(fm, key) {
  const re = new RegExp(`^${key}:\\s*(.+)$`, 'm');
  const m = re.exec(fm);
  if (!m) return null;
  let v = m[1].trim();
  if (v.startsWith('"') && v.endsWith('"')) { try { v = JSON.parse(v); } catch { /* keep */ } }
  return v;
}
/** Read a YAML block-sequence list (` - item` lines) under `key:`. */
function fmList(fm, key) {
  const lines = fm.split('\n');
  const out = [];
  let i = lines.findIndex(l => l === `${key}:`);
  if (i === -1) return null;
  for (i = i + 1; i < lines.length; i++) {
    const m = /^ - (.+)$/.exec(lines[i]);
    if (!m) break;
    let v = m[1].trim();
    if (v.startsWith('"') && v.endsWith('"')) { try { v = JSON.parse(v); } catch { /* keep */ } }
    out.push(v);
  }
  return out;
}

const all = buildAll();

// --- the generated set matches the expected agent list -----------------------
const EXPECTED_FILES = ['architect.md', 'designer.md', 'developer.md', 'devops-engineer.md',
  'fixer.md', 'guardian.md', 'qa-engineer.md', 'researcher.md', 'reviewer.md'];
ok('generated set matches the expected 9-agent list',
  JSON.stringify([...all.keys()].sort()) === JSON.stringify([...EXPECTED_FILES].sort()));
ok('NATIVE_AGENTS declares exactly the expected files',
  JSON.stringify(NATIVE_AGENTS.map(a => a.file).sort()) === JSON.stringify([...EXPECTED_FILES].sort()));
ok('excludes internal/temporary/subagent types (volundr, planner, *-voice, developer-subagent, tester, content)',
  !NATIVE_AGENTS.some(a => ['volundr', 'planner', 'roundtable-voice', 'chaos-engine-voice', 'developer-subagent', 'tester', 'content'].includes(a.type)));

// --- every def has valid frontmatter + correct model/tools -------------------
for (const { type, file } of NATIVE_AGENTS) {
  const def = AGENT_REGISTRY_DATA[type];
  const content = all.get(file);
  const { fm, body, ok: parsed } = splitDef(content);
  const name = file.replace(/\.md$/, '');

  ok(`${file}: has well-formed --- frontmatter --- block`, parsed);
  ok(`${file}: name == dispatch name "${name}"`, fmScalar(fm, 'name') === name);
  ok(`${file}: description matches registry`, fmScalar(fm, 'description') === def.description);
  ok(`${file}: model is the short alias "${shortModel(def.model)}"`, fmScalar(fm, 'model') === shortModel(def.model));

  const tools = fmList(fm, 'tools') || [];
  const expectedTools = resolveTools(def);
  ok(`${file}: tools list matches resolveTools (registry tools + team tools)`,
    JSON.stringify(tools) === JSON.stringify(expectedTools));
  // every registry tool is present in the emitted tools
  ok(`${file}: every registry tool is present`, def.tools.every(t => tools.includes(t)));

  const disallowed = fmList(fm, 'disallowedTools') || [];
  ok(`${file}: disallowedTools is the complement of allowed`,
    JSON.stringify(disallowed) === JSON.stringify(resolveDisallowedTools(tools)));
  ok(`${file}: no tool appears in both tools and disallowedTools`,
    !disallowed.some(t => tools.includes(t)));

  // --- ISC-4: body pointer equals the registry promptTemplate (not the stale path)
  ok(`${file}: body points at registry promptTemplate "${def.promptTemplate}"`,
    body.includes(def.promptTemplate));
  ok(`${file}: body does NOT use the stale framework/agents/prompts/ path`,
    !body.includes('framework/agents/prompts/'));
  ok(`${file}: carries the GENERATED / DO NOT EDIT banner`, body.includes('GENERATED by'));

  // whenToUse cue (ISC-7) emitted when present
  if (def.whenToUse) {
    ok(`${file}: emits the whenToUse delegation cue`, body.includes(def.whenToUse));
  }

  // maxTurns mirrored when set
  if (typeof def.maxTurns === 'number') {
    ok(`${file}: maxTurns == ${def.maxTurns}`, fmScalar(fm, 'maxTurns') === String(def.maxTurns));
  }
}

// --- ISC-2: read-only roles carry permissionMode: plan -----------------------
for (const [type, file] of [['architect', 'architect.md'], ['guardian', 'guardian.md'], ['review', 'reviewer.md']]) {
  const { fm } = splitDef(all.get(file));
  ok(`${file} (read-only role "${type}"): permissionMode == plan`, fmScalar(fm, 'permissionMode') === 'plan');
  const tools = fmList(fm, 'tools') || [];
  ok(`${file}: read-only role has no Write/Edit in tools`, !tools.includes('Write') && !tools.includes('Edit'));
}
// write-capable agents must NOT carry plan
for (const file of ['developer.md', 'designer.md', 'devops-engineer.md', 'qa-engineer.md', 'researcher.md', 'fixer.md']) {
  const { fm } = splitDef(all.get(file));
  ok(`${file}: write-capable role does NOT set permissionMode plan`, fmScalar(fm, 'permissionMode') !== 'plan');
}

// --- ISC-1: mcpServers referenced for agents whose pack has a .mcp.json -------
{
  const { fm } = splitDef(all.get('researcher.md'));
  ok('researcher.md: references its research pack mcpServers (playwright + atlassian + microsoft-learn)',
    /mcpServers:/.test(fm) && /playwright:/.test(fm) && /atlassian:/.test(fm) && /microsoft-learn:/.test(fm));
}
{
  const { fm } = splitDef(all.get('devops-engineer.md'));
  ok('devops-engineer.md: references its infrastructure pack mcpServers (azure)',
    /mcpServers:/.test(fm) && /azure:/.test(fm));
}
{
  // core-pack agents have no .mcp.json -> no mcpServers block
  const { fm } = splitDef(all.get('developer.md'));
  ok('developer.md (core pack, no .mcp.json): emits no mcpServers block', !/mcpServers:/.test(fm));
}

// --- idempotency: generate -> generate yields byte-identical content ----------
{
  const a = buildAll();
  const b = buildAll();
  let identical = a.size === b.size;
  for (const [k, v] of a) if (b.get(k) !== v) identical = false;
  ok('generator is idempotent (buildAll twice -> byte-identical)', identical);

  // renderAgent is pure: same inputs -> same output
  const def = AGENT_REGISTRY_DATA.developer;
  ok('renderAgent is deterministic for identical inputs',
    renderAgent('developer', def, 'developer') === renderAgent('developer', def, 'developer'));
}

// --- on-disk defs match the generator (the committed files were regenerated) --
// EOL-agnostic: core.autocrlf=true may give the working tree CRLF on a fresh checkout.
{
  const lf = (s) => (s == null ? s : s.replace(/\r\n/g, '\n'));
  let allMatch = true;
  const mismatched = [];
  for (const [file, content] of all) {
    const path = join(AGENTS_DIR, file);
    const onDisk = existsSync(path) ? readFileSync(path, 'utf8') : null;
    if (lf(onDisk) !== lf(content)) { allMatch = false; mismatched.push(file); }
  }
  ok(`on-disk .claude/agents/*.md match the generator${mismatched.length ? ' (drift: ' + mismatched.join(', ') + ')' : ''}`, allMatch);
}

// --- summary -----------------------------------------------------------------
console.log(`\n${pass} passed, ${fail} failed`);
process.exit(fail === 0 ? 0 : 1);
